### ISSUE TITLE
too based

### ISSUE THREAD

**Issue by KatAsh1917** [JoelLucaAdams/personal-and-professional-issues#1]
your two based, sorry joel

**Comment by itsmichaelwest** [comment]
i agree

**Comment by itsmichaelwest** [comment]
![image](https://user-images.githubusercontent.com/19785650/119388778-aa31cd80-bcc2-11eb-9845-6aa436301152.png)

**Comment by Jack-Prosser** [comment]
> your two based, sorry joel

https://www.waterstones.com/book/english-grammar-for-dummies/lesley-j-ward/geraldine-woods/9780470057520

**Comment by JoelLucaAdams** [comment]
Thanks for the positive feedback guys
